apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: vibrint
  #namespace: ansible-automation-platform
  namespace: aap
spec:
  adminUser:
    username: admin
    passwordSecret:
      name: aap-admin-password-secret
      key: password
  database:
    resource_requirements:
      requests:
        cpu: 200m
        memory: 512Mi
    storage_requirements:
      requests:
        storage: 100Gi
  # Platform
  image_pull_policy: IfNotPresent
  # Components
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: false
    ## Modify to contain your RWM storage class name
    storage_type: file
    file_storage_storage_class: ocs-storagecluster-cephfs
    file_storage_size: 10Gi

    ## uncomment if using S3 storage for Content pod
    storage_type: S3
    object_storage_s3_secret: galaxy-object-storage

  lightspeed:
    disabled: true
